version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: minelibrary-postgres-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: library_management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  library-adp: 
    container_name: libraryadp
    build: 
      context: ./library-adp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  library-client: 
    container_name: libraryclient
    build: 
      context: ./library-client
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

volumes:
  postgres-data:
